const values=[1,2];
values.push(3);
console.log(values);
values.pop();
console.log(values);
values.shift();
console.log(values);
values.unshift(10);
console.log(values);
console.log(values.length);
console.log(values[0]);